from . import product_template
from . import pc_build
from . import rma_request
from . import price_alert
from . import stock_alert
from . import sale_followup
from . import purchase_request
from . import stock_control
from . import crm_ticket
